### ISSUE TITLE
Indicate how to use bioc-devel with R-devel in the mid-April to mid-October time frame?

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/pkgrevdocs#108]
- From discussion at https://stat.ethz.ch/pipermail/bioc-devel/2023-May/019678.html
- Relevant section https://github.com/Bioconductor/pkgrevdocs/blob/devel/devel-branch.Rmd

The suggestion from the thread is

```
## use Sys.setenv() before setRepositories
Sys.setenv(R_BIOC_VERSION="3.18")
setRepositories(ind = 1:4) # CRAN plus Bioc soft, anno, and expt repos
getOption("repos")    # check
install.packages("BiocGenerics")
```

This isn't satisfactory because, for instance, it does not include the 'books' repository An alternative might be 

```
## sub() magic on BiocManager::repositories() to replace current Bioc version with desired version
pattern <- ??? ## magic to reliably identify Bioconductor version in `BiocManager::repositories()`
desired_version - "3.18"
all_repos <- sub(pattern, desired, BiocManager::repositories())
options(repos = all_repos)
```

This would require thorough testing.

It is worth deciding that this is the right thing to do

- There is no use case for most Bioconductor package developers to be using a combination of R and Bioconductor versions that is not directly supported by BiocManager. The above allows a package developer to use an **incorrect** installation, e.g.,  developing code assuming that the user and other developers will see the behavior of R-devel, when actually they will see the behavior of the current R-release.
- A use case might be for a CRAN package developer wishing to test their package on R-devel, or for a Bioconductor package developer wishing to test that CRAN packages that depend on their package will work on R-devel.

**Comment by wolfganghuber** [comment]
As you correctly point out,  Bioconductor package developers are probably **not** those with the most relevant use cases. I think there are use cases for everyone else—anyone who decides to write code on R-devel, for whatever reason, and just wants to **use** a Bioconductor package between mid-April to mid-October  (they could develop for CRAN, or just be a user and write scripts and packages for a private project). There are many useful packages on Bioconductor that are of general interest, even for people whose work does not center around Bioconductor or biology... (say, ggtree, rhdf5, sparseMatrixStats, EBImage, ...)

**Comment by lshep** [comment]
I've suggested before that BiocManager should default to the current devel whenever an unsupported version (ie. the next version of R-devel in this in between period) but have been overruled in the past? Assuming it would work the same as when we release a new version of Bioc for the same version of R,  that once fall release roles around and when we have a version that is officially supported, that it gives a warning that there is an updated version of Bioc for your version of R and asks if a user wants to update

**Comment by mtmorgan** [comment]
Another possibility is to add `validate_version = TRUE` to `repositories()` and `install()`, allowing users to install arbitrary package versions.

**Comment by mmaechler** [comment]
If it was ok, to declare using Bioc version "3.18"  at this point in time, in my setup I would also install all Bioc packages
into a library `..../Bioconductor/library_3.18/`   with the nice advantage that I could *continue* using that package library once (in fall) that Bioc version will spring into official existence.

**Comment by wolfganghuber** [comment]
There was also a comment by Martin Mächler: https://stat.ethz.ch/pipermail/bioc-devel/2023-May/019690.html

**Comment by wolfganghuber** [comment]
I like the union of Lori's and both Martins' suggestions of yesterday.
Note that Martin Mächler's suggestion would make Bioconductor more consistent with R/CRAN:

```
> R.version
               _                                                 
platform       aarch64-apple-darwin20                            
arch           aarch64                                           
os             darwin20                                          
system         aarch64, darwin20                                 
status         Under development (unstable)                      
major          4                                                 
minor          4.0                                               
year           2023                                              
month          05                                                
day            05                                                
svn rev        84398                                             
language       R                                                 
version.string R Under development (unstable) (2023-05-05 r84398)
nickname       Unsuffered Consequences                           

```

**Comment by wolfganghuber** [comment]
My impression is that this discussion is a conflict between to basic worldviews:
- Bioconductor as a tight ecosystem where everything depends on everything and is not useful without everything
- Bioconductor as a “loose” package repository, like CRAN, just better
I think we need to accommodate both  and should not pretend only the first is valid.

I also note that we have many important packages on Bioconductor with no Bioconductor dependencies:  BiocParallel, illuminaio, rhdf5, EBImage, ggtree, edgeR, limma, qvalue, sparseMatrixStats, …

**Comment by mmaechler** [comment]
I agree, other really important packages are  `graph`, `Rgraphviz`, etc.
 One advantage of going there would also be more general exposure to the R world outside Bioc.

At the moment, R package developers (outside Bioc) are sometimes seriously considering *not* to have their package depend on a good Bioc package only just because for their users (and partly even themselves) it is such a pain sometimes to even get a correct installation of their package.

An anectode: Recently a smart finishing Phd student (who is also a CRAN package maintainer) approached me because she did not succeed to install CRAN package `pcalg` (of which I am co-author),  the reason being that `pcalg` does strongly depend on `graph` and `Rgraphviz`  and on her laptop bioconductor repositories where not (correctly) visible  ((not properly part of here `getOption("repos")`))  and course, nowadays, users used to click in Rstudio to install packages often have no clue what to do if the clicking fails {{in her case, there was the added problem of binary vs source packages on the Mac ..}}.

**Comment by lshep** [comment]
So then maybe Bioconductor default repositories should be added to default R provided repos / Rstudio default provided repos?  Or better documentation on how this can be done on those sites?  Even if we make things easier and more documented on Bioconductor side this problem would still remain; would it not?  because R doesn't by default include Bioconductor repositories?

**Comment by mtmorgan** [comment]
For instance, if everything in '[repositories](https://github.com/wch/r-source/blob/trunk/etc/repositories)' were part of `getOption("repos")`? `install.packages()` would 'just work' for Bioconductor package dependencies, and R-core would still play 'gatekeeper' via updates to the repositories file & `utils:::.BioC_version_associated_with_R_version`.

**Comment by mmaechler** [comment]
I'd definitely be happy with adding that, or minimally `BioCsoft` if that would make it easier.

**Comment by vjcitn** [comment]
Learning here.  So without any changes we can use, in R-patched and R-devel,
```
setRepositories(name = c("CRAN", "BioCsoft", "BioCann", "BioCexp"))
```
and `install.packages` will install Bioconductor packages from the Bioconductor version identified by the value of `Sys.getenv("R_BIOC_VERSION")`, whereas `BiocManager::install` will throw an error when attempted in R-devel in the interval from April to October.  One feature that is lost is the checking against current installations -- if version v of package p is already installed, BiocManager::install will require `force=TRUE` to perform reinstallation.  This has been useful to deal with unneeded installation requests that are scripted or performed robotically, for which we pay egress fees.

**Comment by mtmorgan** [comment]
For what it's worth 433 of 19547 CRAN packages use 158 Bioc packages from the software, annotation, and experiment repositories.

```
cran <- available.packages(repos = "https://cran.r-project.org")
bioc <- available.packages(repos = BiocManager::repositories()[1:5])

cran_deps <-
    tools::package_dependencies(rownames(cran), cran, recursive = FALSE)

cran_deps0 <- relist(unlist(cran_deps) %in% rownames(bioc), cran_deps)

Filter(any, cran_deps0) |> length()
## [1] 433
length(cran_deps0)
## [1] 19547

bioc_deps <- unlist(cran_deps)[unlist(cran_deps) %in% rownames(bioc)]

table(bioc[unique(bioc_deps), "Repository"])

##            https://bioconductor.org/packages/3.18/bioc/src/contrib 
##                                                                142 
## https://bioconductor.org/packages/3.18/data/annotation/src/contrib 
##                                                                 14 
## https://bioconductor.org/packages/3.18/data/experiment/src/contrib 
##                                                                  2 
```

`setRepositories()` doesn't have a `name=` argument, and the order of repositories is not guaranteed, so the user would have to figure out that they wanted `setRepositories(ind = 1:4)`

As noted above, R doesn't know about the workflow and books repositories.

Using the environment variable `R_BIOC_VERSION` seems like a real 'power tool' where any R version can be configured for any Bioconductor version. It would be better (in my opinion) to let R's internal logic give an imperfect recommendation (R-4.3.x will always reference Bioc-3.17, even when Bioc-3.18 becomes available after the next Bioc release; R-devel currently recommends 3.17 even though 3.18 is more appropriate).

I did open a PR to allow BiocManager to install under R-devel; whether that's the right thing to do is really a policy decision.

**Comment by llrs** [comment]
I have a suggestion: Maybe if Bioconductor set an alias it would help to minimize the friction. 
Something along `https://bioconductor.org/packages/release/bioc/src/contrib` to be used and then Bioconductor change the redirect of this path from `https://bioconductor.org/packages/3.17/bioc/src/contrib` to `https://bioconductor.org/packages/3.18/bioc/src/contrib` in October/November.

---

From the [R-repository working group](https://github.com/RConsortium/r-repositories-wg/) we wanted to know how could a new repository become official/recognized by CRAN/R Core and how would that play with the existing repositories: For example, there was a proposal to create a new CRAN-like repository for FDA submissions. This discussion is very interesting about the efforts required to minimize friction for users and developers between repositories.

**Comment by lshep** [comment]
@llrs  `https://bioconductor.org/packages/release/bioc/src/contrib` and `https://bioconductor.org/packages/devel/bioc/src/contrib`  already exist as symlinks and point accordingly on our system

**Comment by llrs** [comment]
Thanks @lshep, I wasn't sure if the error message I got was because it existed or something else (https://bioconductor.org/packages/release/bioc/src/contrib/ (Error 403) vs https://bioconductor.org/packages/3.14/bioc/src/contrib/ (NoSuchKey)). But now I see that for 3.15 and 3.16 the error is the same 403.

**Comment by lshep** [comment]
3.15 and 3.16 are currently still hosted on AWS bioconductor.org cloudfront but this will change shortly (in the next week or two when we move them to legacy) . Older releases are hosted on the OSN.  Which is why you see the difference in error/output.

**Comment by lshep** [comment]
This seems to be resolved 

```
> library(BiocManager)
Bioconductor does not yet build and check packages for R version 4.5, using
  unsupported Bioconductor version 3.20; see https://bioconductor.org/install

```
