### ISSUE TITLE
rename GH repository to match URL advertised

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/pkgrevdocs#24]
Contributions is already a repository under Bioconductor. Perhaps we could rename it to guidelines?

**Comment by LiNk-NY** [comment]
The URL can also change as long as we have a redirect entry.

I've also found it hard to remember the repository name if I want to go straight to the GH repo. 
Perhaps we can come up with a list of options for potential renames (here are a few): 

| WebsiteURL | Repo_Option1 | Repo_Option2 |
|------------|---------| ----------- |
| contributions.bioconductor.org | contributions.bioconductor.org | pkgrevdocs |
| guidelines.bioconductor.org | guidelines.bioconductor.org | guidelines |
| devguide.bioconductor.org | devguide.bioconductor.org | devguide | 

The last row is based on [rOpenSci's](https://devguide.ropensci.org/building.html) naming scheme.

**Comment by lshep** [comment]
The package review committee reviewed and voted on this request.  We stand by the original decision of contributions.bioconductor.org as the endpoint url.  This was done on purpose with the github Contributions repo as we felt like the users and those contributing package would better be able to find where to submit packages.  

There are links to the source code displayed on the contributions.bioconductor.org pages as well as direct links to edit this page.  The handful that would search for the directory directly by first going to the github organization that experience this confusion are minimal (2-3) and we feel don't out-way the benefit for the intention of the pages.  

Also justification: we have the funding awarded to investigate and hire a web developer to evaluate and update the website. We should see what recommendations to link this person will advise which may involve additional renaming.  We would like to avoid multiple renaming and redirects if possible and will evaluate based on any feedback given at that time.  

As a compromise please see the above referenced issue #37 for better advertised links to source code from the website.

**Comment by LiNk-NY** [comment]
Thanks for looking into this. 

I don't think the repository name should be very different from the website URL. 
Similar to the https://bioconductor.org website GitHub repository, https://github.com/Bioconductor/bioconductor.org, it is easier to associate the current website https://contributions.bioconductor.org with a similarly named repository e.g., https://github.com/Bioconductor/contributions.bioconductor.org. 
The change in the repository name would likely _not_ be disruptive and would help towards having a consistent naming scheme. 

Best,
Marcel
