### ISSUE TITLE
biocViews

### ISSUE THREAD

**Issue by llrs** [Bioconductor/pkgrevdocs#34]
biocViews is currently both on the [Description](http://contributions.bioconductor.org/description.html#biocviews) and on its [own chapter](http://contributions.bioconductor.org/biocviews-1.html). Perhaps the content could be inserted inside the Description chapter or at least a link to the section (although biocViews is the next chapter). 

The url of biocviews chapter is: http://contributions.bioconductor.org/biocviews-1.html instead of http://contributions.bioconductor.org/biocviews.html despite being the  file 03a-biocViews.Rmd. 
Not sure what is going on there.  
I thought that this could be to the naming of the chapter but found out that other chapter following the same pattern do not have the -1 appended. While looking this I found there is one inconsistencie naming the files of chapters: `11-c-fortran.Rmd` instead of `11c-fortran.Rmd`.

**Comment by llrs** [comment]
Many thanks for the clarifications! I think you are right about the url and the duplicate titles. Sorry I missed the content of the section. 

I'll leave the issue open as a reminder when the content has been moved and the time to re-organize and clean up comes.

**Comment by lshep** [comment]
I have reorganized many files and added specific headers to avoid duplication.  Some sections and concepts are repeated throughout to emphasize Bioconductor specific requirements
