### ISSUE TITLE
New requirements for package submissions

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/pkgrevdocs#59]
Following up from discussion at the Bioconductor retreat in Heidelberg and the increasing redundancy in packages/functions, I would like to propose the following requirement/expectation for new packages:

The authors should provide the following as part of the vignette introduction:

1. A short motivation for the package in general, and for the inclusion of their package in Bioconductor in particular.

2. When relevant, a brief review and comparison of packages with similar functionality or scope, based for example on biocViews.

The rationale for these new *soft* requirements is that a package might be very useful, but not necessarily a good fit with Bioconductor, and such an intro could help (future) authors think about that fit. This is also an opportunity for maintainers to highlight how their package is a good Bioconductor citizen, how it complements existing packages, or fulfils a new niche. Finally, it will be extremely useful for users to learn about similar packages when reading a vignette, a bit alike the *See also* section in manual pages.

I am happy to
- send a PR the guidelines book
- add an item in template for reviewers

Ping @lshep 
Cc @vjcitn

**Comment by lshep** [comment]
That sounds excellent and I always welcome PRs.  I think @vjcitn also suggested using code.bioconductor.org (when choosing package name or function name) to see if there is any existing -- pointing it out as it might make sense to add this to package name and function development sections too based on recent reviews and for comparison
